material ui config & directory tree setup
luisiacc/mri-segmentation pull request #3
Opened 2021-05-02 16:53 UTC by raultorre

Closes #1, closes #2

2021-05-02 18:33 UTC, luisiacc requested changes
Tengo una duda general sobre poner las carpetas `theme` y `query` bajo `utils`, me parece que deberían ser una carpeta al mismo nivel que `utils`, o incluso `theme` puede ser hasta un solo archivo por el momento, pienso que son cosas que no son catalogadas como `utiles`.

2021-05-02 18:33 UTC, luisiacc commented on webui/package.json
> +    "react-query": "^3.15.2",
👍

2021-05-02 18:33 UTC, luisiacc commented on webui/src/utils/query/conf.ts
> +  axiosQuery({ method: "post", url: url, config: { data } })
Tengo algunas dudas sobre bindear `data` a `DataType`, me parece que a este nivel de abstracción lo mas correcto es simplemente decir que `data` sea `Object`.

2021-05-16 13:38 UTC, raultorre commented on webui/src/utils/query/conf.ts
> +  axiosQuery({ method: "post", url: url, config: { data } })
Pienso que no cada vez que se cambie el objeto de entrada se cambiaria el type en correspondencia Object es un type muy generico y romperia el proposito de usar los @types

2021-05-16 13:39 UTC, merged